<?php

namespace Ais\PertemuanBundle\Repository;

/**
 * PertemuanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PertemuanRepository extends \Doctrine\ORM\EntityRepository
{
}
